#!/bin/sh

dir="$1"

if [ "$dir" = "" ]
then
    echo "Sorry, you must give me a directory to burn!"
    exit 1
fi

if [ "" != "$2" ]
then
	echo "No second argument allowed"
	exit 1
fi

volumeid="$dir"
[ "$VOLUMEID" != "" ] && volumeid="$VOLUMEID"
name="$(getent passwd "$USER" | cut -d ':' -f 5 | cut -d ',' -f 1)"
publisher="$name"
preparer="$name"

echo "Burning to CD:    $dir"
echo "Volume ID:        $volumeid"
echo "Publisher:        $publisher"
echo "Preparer:         $preparer"
echo ""
echo "mkisofs  options: $MKISOFS_OPT"
echo "cdrecord options: $CDRECORD_OPT"
echo


mkisofs \
	-volid "$volumeid" \
	-preparer "$preparer" \
	-publisher "$publisher" \
	-joliet -r \
	-translation-table \
	-v ${MKISOFS_OPT} \
	"$dir" \
| cdrecord \
	dev=ATAPI:0,0,0 \
	driveropts=burnfree \
	-verbose -verbose -eject \
	-waiti ${CDRECORD_OPT} \
	-data -

