#!/usr/bin/python


import re
import subprocess
import sys
import time


def main():
    r = re.compile(r'^(ftp|https?)://', re.IGNORECASE)
    last_sel = ''
    while True:
        next_sel = subprocess.check_output(['xsel', '-o'])
        if last_sel != next_sel:
            last_sel = next_sel
            m = r.match(last_sel)
            if m:
                sys.stdout.write('%s\n' % last_sel)
                sys.stdout.flush()
        time.sleep(1)


if __name__ == '__main__':
    main()
