#!/bin/bash
#
# Syntax: percheck file1 file2 ...
#
# displays permissions of all files and all directories above
#

file="$1"

while shift
do
    until false
    do
        if [ "$file" = "." ]
        then
            file="$(pwd)"
        fi
        ls -ald "$file"
        if [ "$file" = "/" ]; then break; fi
        file="$(dirname "$file")"
    done
    file="$1"
done
