#!/bin/bash

# I recommend you either
# a) Run in the background and redirect input and output
# b) Do neither of that.

tla archive-mirror \
    "${ARCH_ARCHIVE}" "${ARCH_ARCHIVE}-MIRROR" \
    "${ARCH_CATEGORY}" < /dev/null >& /dev/null &

exit 0
