#!/bin/bash

if [ "$ARCH_REVISION" = "" ]; then
    echo "$0 called without ARCH_REVISION set. Aborting."
    exit 1
fi

arch_summary_domain="arch.n-dimensional.de"
email="${ARCH_ONLY_CATEGORY}-summary@${arch_summary_domain}"

# We may want to start that as a background process if it starts to
# take too long...
(
echo "From: $(tla my-id)"
echo "Date: $(date)"
echo "Subject: Summary for ${ARCH_REVISION}"
echo "To: ${ARCH_ONLY_CATEGORY} arch summaries <${email}>"
echo
tla cat-archive-log "${ARCH_ARCHIVE}/${ARCH_REVISION}"
echo
dir="${ARCH_REVISION}.changeset-$$"
tla get-changeset "${ARCH_REVISION}" "${dir}"
tla show-changeset --diffs "${dir}"
rm -rf "${dir}"
) | /usr/sbin/sendmail "${email}"

exit 0
