name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      fetch-depth: 0
    - name: env-info
      run: ./.github/scripts/env-info.sh
      shell: sh
    - name: autoreconf
      run: autoreconf -vis .
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
